title = 'DZa test - 30102023'
baseURL = "http://localhost:1313/"

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false
# theme = 'docura'
