title = 'Docura'
baseURL = 'https://diegoazabalab.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = ''

enableGitInfo = true

markup.highlight.noClasses = false
# theme = 'docura'
